# Generated by Django 5.0.7 on 2024-08-12 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='blog_likes_count',
            field=models.IntegerField(default=0),
        ),
    ]
