# Generated by Django 5.0.7 on 2024-07-30 16:07

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='title_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='blog_title', unique=True),
        ),
    ]
